title: "Energy Typography "
description: "Hi, I'm Geronimo Villaveces, a second year student in Oxfrod
  Brookes. I made this website to show the different types of typograpgy on the Energy Drinks "
header_text: "Types of Typography on Energy Drinks "
footer_text: "Copyright 2020 Geronimo Villaveces Schenk "
header_feature_image: ../uploads/background-2.webp
bannerheight: 20vmax
logo: ../uploads/49993860_561514860988941_4833417294469051420_n.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
