title: "Student Hobbies "
description: "Hi, I'm Geronimo Villaveces, a second year student in Oxfrod
  Brookes. I made this website to show students their different options when
  looking for a hobby. I will do my best to show the costs and how compatible it
  is with uni life. "
header_text: "What options do uni students have for Hobbies? "
footer_text: "Copyright 2020 Geronimo Villaveces Schenk "
header_feature_image: ../uploads/background-2.webp
bannerheight: 20vmax
logo: ../uploads/49993860_561514860988941_4833417294469051420_n.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
