title: "Student Hobbies "
description: ""
header_text: "What Options Do University Students Have For Hobbies? "
footer_text: "Copyright 2020 Geronimo Villaveces Schenk "
header_feature_image: ../uploads/background-2.webp
bannerheight: 20vmax
logo: ../uploads/49993860_561514860988941_4833417294469051420_n.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
